# Generated by Django 4.0.8 on 2023-04-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonSite', '0002_alter_package_ups_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='track_num',
        ),
        migrations.AddField(
            model_name='package',
            name='truck_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
