# Generated by Django 4.1.5 on 2023-04-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonSite', '0005_remove_order_order_status_package_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
