# Generated by Django 4.1.5 on 2023-04-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazonSite', '0006_order_order_status_alter_package_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_ups',
            name='bind_status',
            field=models.CharField(blank=True, default='checking', max_length=100, null=True),
        ),
    ]
